- name: Create/Modify a Record Set Route 53 on private zone
  hosts: "{{target}}"
  tasks: 

  - name: "Creating Route 53-> {{record_set}} with value -> {{record_value}}"
    route53:
      command: create
      zone: "{{hosted_zone}}"
      record: "{{record_set}}"
      type: "{{record_type}}"
      ttl: 60
      value: "{{record_value}}"
      overwrite: yes
      private_zone: true
      vpc_id: "{{vpc_id}}"
    register: route53_output

  - debug: var=route53_output