- name: Delete an RDS instance and Take Snapshot before doing so
  hosts: "{{target}}"
  tasks:

  - name: "Deleting {{rds_instance}}"
    rds:
      command: delete
      region: "{{region | default('us-east-1')}}"
      instance_name: "{{rds_instance}}"
      snapshot: "{{rds_bkp_snapshot}}"
    register: rds

  - debug: var=rds
  
  - name: Debug RDS facts status deleting
    rds:
      command: facts
      instance_name: "{{rds_instance}}"
      region: "{{region | default('us-east-1')}}"
    register: rds_facts
    until: rds_facts.instance.status == "deleting"
    retries: 5
    delay: 15
    ignore_errors: True

  - name: Debug RDS facts endpoint is none
    rds:
      command: facts
      instance_name: "{{rds_instance}}"
      region: "{{region | default('us-east-1')}}"
    register: rds_facts
    until: (rds_facts.instance.endpoint is none)
    retries: 40
    delay: 30
    
  - debug: var=rds_facts